[build-system]
requires = [
    "scikit-build-core",
    "nanobind",
    "numpy",
    "pyqt5",
    "pydantic",
]
build-backend = "scikit_build_core.build"

[project]
name = "pairinteraction"
version = "0.9.10"
description = "A Rydberg Interaction Calculator"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "GPL-3.0-or-later OR LGPL-3.0-or-later" }
authors = [
    { name = "Sebastian Weber" },
    { name = "Henri Menke" },
]
dependencies = [
    "numpy",
    "pint",
    "pyqt5",
    "pyqtgraph",
    "scipy",
    "pydantic",
]

[project.urls]
Homepage = "https://www.pairinteraction.org"
Repository = "https://github.com/pairinteraction/pairinteraction"

[tool.scikit-build]
cmake.verbose = true
wheel.packages = []
wheel.py-api = "py3"

[tool.cibuildwheel]
build = [
  "cp39-manylinux_x86_64",
  "cp39-win_amd64",
  "cp39-macosx_x86_64",
]
build-verbosity = 1
test-command = [
  "python -c \"import pairinteraction\"",
  "python -c \"from pairinteraction_gui import app; assert type(app.version_program) is str\"",
]

[tool.cibuildwheel.windows]
before-all = "pip install delvewheel" # build-system.requires is unavailable in the build venv
repair-wheel-command = "delvewheel repair --ignore-in-wheel -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos.environment]
MACOSX_DEPLOYMENT_TARGET = "13.0"
