name: Windows

on: [push, pull_request]

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2
  CMAKE_BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ hashFiles('vcpkg.json') }}-${{ runner.os }}-cache-key-v1

      - uses: actions/setup-python@v3
        with:
          python-version: '3.6'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build/ -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=${{ env.CMAKE_BUILD_TYPE }} -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DWITH_DOCS=FALSE -DCMAKE_TOOLCHAIN_FILE="%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake"
          cmake --build build/ --config ${{ env.CMAKE_BUILD_TYPE }}

      - name: After build
        run: |
          $RedistVersion = Get-Content "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt" -TotalCount 1
          Copy-Item -Path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Redist\MSVC\$($RedistVersion.Trim())\vcredist_x64.exe" -Destination vcredist_x64.exe -Verbose
          cmake --build . --target win32 --config ${{ env.CMAKE_BUILD_TYPE }}
          python setup.py bdist_wheel --python-tag py3 --plat-name win_amd64
          $env:PATH_WHEEL_UNMODIFIED=$(ls dist\*.whl | foreach { $_.FullName })
          wheel unpack $env:PATH_WHEEL_UNMODIFIED -d wheelhouse\
          $env:PATH_WHEEL_UNPACKED=$(ls wheelhouse\* | foreach { $_.FullName })
          xcopy pairinteraction\Release\* ${env:PATH_WHEEL_UNPACKED}\pairinteraction\
          Remove-Item –path $env:PATH_WHEEL_UNPACKED\*.dist-info\RECORD
          wheel pack $env:PATH_WHEEL_UNPACKED -d wheelhouse\
        working-directory: build/

      - name: Tests
        run: |
          xcopy pairinteraction\Release\* pairinteraction
          cmake --build . --target check --config ${{ env.CMAKE_BUILD_TYPE }}
        working-directory: build/

      - uses: actions/upload-artifact@v3
        with:
          name: pairinteraction-install-windows.exe
          path: build/pairinteraction-install-windows.exe
